### ISSUE TITLE
Error executing action `install` on resource 'chef_gem[pg]'

### ISSUE THREAD

**Issue by joelhandwell** [gospelandit/chef-odoo#3]
Following error shows up while ```kitchen converge```:
```
         * chef_gem[pg] action install

           ================================================================================
           Error executing action `install` on resource 'chef_gem[pg]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.19.0" ----
           STDOUT: Building native extensions.  This could take a while...
           STDERR: ERROR:  Error installing pg:
                ERROR: Failed to build gem native extension.

        current directory: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/pg-0.19.0/ext
           /opt/chef/embedded/bin/ruby -r ./siteconf20170104-15671-169viii.rb extconf.rb
           checking for pg_config... yes
           Using config values from /usr/bin/pg_config
           checking for libpq-fe.h... yes
           checking for libpq/libpq-fs.h... yes
           checking for pg_config_manual.h... yes
           checking for PQconnectdb() in -lpq... no
           checking for PQconnectdb() in -llibpq... no
           checking for PQconnectdb() in -lms/libpq... no
           Can't find the PostgreSQL client library (libpq)
           *** extconf.rb failed ***
           Could not create Makefile due to some reason, probably lack of necessary
           libraries and/or headers.  Check the mkmf.log file for more details.  You may
           need configuration options.

           Provided configuration options:
                --with-opt-dir
                --with-opt-include
                --without-opt-include=${opt-dir}/include
                --with-opt-lib
                --without-opt-lib=${opt-dir}/lib
                --with-make-prog
                --without-make-prog
                --srcdir=.
                --curdir
                --ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
                --with-pg
                --without-pg
                --enable-windows-cross
                --disable-windows-cross
                --with-pg-config
                --without-pg-config
                --with-pg_config
                --without-pg_config
                --with-pg-dir
                --without-pg-dir
                --with-pg-include
                --without-pg-include=${pg-dir}/include
                --with-pg-lib
                --without-pg-lib=${pg-dir}/lib
                --with-pqlib
                --without-pqlib
                --with-libpqlib
                --without-libpqlib
                --with-ms/libpqlib
                --without-ms/libpqlib

           To see why this extension failed to compile, please check the mkmf.log which can be found here:

             /opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.19.0/mkmf.log

           extconf failed, exit code 1

           Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/pg-0.19.0 for inspection.
           Results logged to /opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.19.0/gem_make.out
           ---- End output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.19.0" ----
           Ran /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.19.0" returned 1

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/postgresql/recipes/ruby.rb:68:in `rescue in from_file'
           /tmp/kitchen/cache/cookbooks/postgresql/recipes/ruby.rb:21:in `from_file'
           /tmp/kitchen/cache/cookbooks/odoo/recipes/database.rb:45:in `from_file'
           /tmp/kitchen/cache/cookbooks/odoo/recipes/default.rb:27:in `from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/postgresql/recipes/ruby.rb

            68:     chef_gem 'pg' do
            69:       compile_time true if respond_to?(:compile_time)
            70:       # allow optional attribute to install specific version of pg gem
            71:       node['postgresql']['pg_gem']['version'] if node['postgresql']['pg_gem']['version']
            72:     end
            73:   rescue Gem::Installer::ExtensionBuildError, Mixlib::ShellOut::ShellCommandFailed => e

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/postgresql/recipes/ruby.rb:68:in `rescue in from_file'

           chef_gem("pg") do
             package_name "pg"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_gem
             cookbook_name "postgresql"
             recipe_name "ruby"
             compile_time true
             gem_binary "/opt/chef/embedded/bin/gem"
           end

           Platform:
           ---------
           x86_64-linux
```

**Comment by joelhandwell** [comment]
Found installation message successful right after the error message:
```
[2017-01-04T05:40:39+00:00] WARN: Failed to properly build pg gem. Forcing properly linking and retrying (omnibus fix)
         * execute[generate pg gem Makefile] action run
           - execute PATH=$PATH:/usr/pgsql-9.5/bin /opt/chef/embedded/bin/ruby extconf.rb
         * execute[make pg gem lib] action run
           - execute make
         * execute[install pg gem lib] action run
           - execute make install
         * execute[install pg spec] action run
           - execute /opt/chef/embedded/bin/gem spec ./cache/pg-0.19.0.gem --ruby > ./specifications/pg-0.19.0.gemspec
       [2017-01-04T05:40:53+00:00] WARN: Installation of pg gem successful!
```
The error was rescued by https://github.com/sous-chefs/postgresql/blob/master/recipes/ruby.rb#L73
