### ISSUE TITLE
uninitialized constant PGconn

### ISSUE THREAD

**Issue by einsty** [gospelandit/chef-odoo#7]
Thanks for the cookbook here.  I was working through a test to get Odoo running on Vagrant - Ubuntu 18.04 with this cookbook and I ran into the following.  Is this anything that you had come across before?

```
==> odoo01: ================================================================================
==> odoo01:     
==> odoo01: Error executing action `create` on resource 'postgresql_database[thirdwave_odoo]'
==> odoo01:     
==> odoo01: ================================================================================
==> odoo01:     
==> odoo01: 
==> odoo01:     NameError
==> odoo01:     ---------
==> odoo01:     uninitialized constant PGconn
==> odoo01:     
==> odoo01:     Cookbook Trace:
==> odoo01:     ---------------
==> odoo01:     /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:132:in `db'
==> odoo01:     /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:97:in `exists?'
==> odoo01:     /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:46:in `block in <class:Postgresql>'
==> odoo01:     
==> odoo01:     Resource Declaration:
==> odoo01:     ---------------------
==> odoo01:     # In /var/chef/cache/cookbooks/odoo/recipes/database.rb
==> odoo01:     
==> odoo01:      43: postgresql_database database do
==> odoo01:      44:   connection connection_info
==> odoo01:      45:   action     :create
==> odoo01:      46: end
==> odoo01:      47: 
==> odoo01:     
==> odoo01:     Compiled Resource:
==> odoo01:     ------------------
==> odoo01:     # Declared in /var/chef/cache/cookbooks/odoo/recipes/database.rb:43:in `from_file'
==> odoo01:     
==> odoo01:     postgresql_database("thirdwave_odoo") do
==> odoo01:       provider Chef::Provider::Database::Postgresql
==> odoo01:       action [:create]
==> odoo01:       default_guard_interpreter :default
==> odoo01:       database_name "thirdwave_odoo"
==> odoo01:       declared_type :postgresql_database
==> odoo01:       cookbook_name "odoo"
==> odoo01:       recipe_name "database"
==> odoo01:       connection {:host=>"127.0.0.1", :port=>5432, :username=>"postgres", :password=>"postgresql_admin_default_password"}
==> odoo01:     end
==> odoo01:     
==> odoo01:     System Info:
==> odoo01:     ------------
==> odoo01:     chef_version=13.4.19
==> odoo01:     platform=ubuntu
==> odoo01:     platform_version=18.04
==> odoo01:     ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> odoo01:     program_name=chef-solo worker: ppid=1621;start=18:14:40;
==> odoo01:     executable=/opt/chef/bin/chef-solo
==> odoo01:     
==> odoo01: [2018-10-22T18:16:39+00:00] INFO: Running queued delayed notifications before re-raising exception
==> odoo01: 
```

**Comment by einsty** [comment]
Noting similar sightings of this error over here in a different project 
https://github.com/dbfit/dbfit/issues/619

**Comment by einsty** [comment]
Confirming that the use of a prior pg_gem version ( 0.2.1 for example ) puts us in another/worse predicament and therefore it does not look like it will be a solution.

**Comment by joelhandwell** [comment]
Seems like it's upstream issue. 
https://github.com/chef-boneyard/database/blob/41cc5a3f4617f431c623e1d67c8d6bafb1e104e8/libraries/provider_database_postgresql.rb#L132
At this line, database cookbook try to access PGconn class but seems not resolved.

Database cookbook depends on postgresql cookbook, and postgresql cookbook made some breaking change. : https://github.com/sous-chefs/postgresql/issues/480

**Comment by joelhandwell** [comment]
Specifying older version of postgresql cookbook might solve this but currently I'm not developing this cookbook. You can fork and fix or send PR, I'll merge.
